export function randomName() {
    const adjectives = ["freeky", "hidden", "bitter", "misty", "silent", "empty", "dry", "dark",
    "summer", "icy", "delicate", "quiet", "white", "cool", "spring", "winter",
    "patient", "twilight", "dawn", "crimson", "wispy", "weathered", "blue",
    "billowing", "broken", "cold", "damp", "falling", "frosty", "green", "long",
    "late", "lingering", "bold", "little", "morning", "muddy", "old", "red",
    "rough", "still", "small", "sparkling", "throbbing", "shy", "wandering",
    "withered", "wild", "black", "young", "holy", "solitary", "fragrant",
    "aged", "snowy", "proud", "floral", "restless", "divine", "polished",
    "ancient", "purple", "lively", "nameless", "shadow", 'airy', 'adamant', 'arcadian', 'comely', 'loudish',
  'likely', 'peaceful', 'colourful', 'restful', 'whybe', 'maybe', 'dammit']
    const nouns = ["waterfall", "river", "breeze", "moon", "rain", "wind", "sea", "morning",
    "snow", "lake", "sunset", "pine", "shadow", "leaf", "dawn", "glitter",
    "forest", "hill", "cloud", "meadow", "sun", "glade", "bird", "brook",
    "butterfly", "bush", "dew", "dust", "field", "fire", "flower", "firefly",
    "feather", "grass", "haze", "mountain", "night", "pond", "darkness",
    "snowflake", "silence", "sound", "sky", "shape", "surf", "thunder",
    "violet", "water", "wildflower", "wave", "water", "resonance", "sun",
    "wood", "dream", "cherry", "tree", "fog", "frost", "voice", "paper", "frog",
    "smoke", "star", 'giant']
    const adjective = adjectives[Math.floor(Math.random() * adjectives.length)]
    const noun = nouns[Math.floor(Math.random() * nouns.length)]
    return adjective + noun
  }
  export function randomAvatar() {
    const avatars = ["Let me fly  you to the moon and back", "I'd like to unzip your files", "Your outfit would look better on the floor of my bedroom", "I love the way you use your dock"]
    const avatar = avatars[Math.floor(Math.random() * avatars.length)]
    return avatar
  }
  export function randomColor() {
    return '#' + Math.floor(Math.random() * 0xFFFFFF).toString(16)
}

  //The usernames are generated by adding a random adjective to a noun, 
  //leading to cool-sounding names like "hiddensnow" or "throbbingfrog". 
  //The colors are generated by generating a random hex number, 
  //while the member's ID is generated by generating a random string.


